package eu.trentorise.smartcampus.universiadi.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;

import eu.trentorise.smartcampus.universiadi.model.Domanda;
import eu.trentorise.smartcampus.universiadi.model.GPS;
import eu.trentorise.smartcampus.universiadi.model.SportObj;

@Controller("sportController")
public class SportController {

	@Autowired
	MongoTemplate db;

	@PostConstruct
	public void init() {
		// mListaAllSport = ContainerSport.getSport();
		db.dropCollection(SportObj.class);

		SportObj x = new SportObj(
				"Alpine",
				0,
				"La disciplina sportiva che cerca di rispondere alla domanda \u00abvediamo chi arriva primo a valle!\u00bb Uno dei pilastri del programma sportivo delle Universiadi, lo sci alpino \u00e8 la disciplina che vanta il maggior livello di partecipazione della manifestazione e solitamente quasi tutti i paesi presenti schierano almeno un atleta al cancelletto di partenza di una delle gare di discesa libera, super G, slalom gigante e slalom, concorrendo anche all\u2019assegnazione della medaglia della \u00abcombinata\u00bb che riunisce almeno tre risultati delle quattro specialit\u00e0. La prima vincitrice universitaria di una medaglia d\u2019oro in una specialit\u00e0 dello sci alpino fu C\u00e9cile Prince, la quale conquisto l\u2019oro per la Francia nel SuperG organizzato sulle piste di Chamonix durante la prima edizione delle Universiadi invernali del 1960.\n\nDurante le Universiadi di Trentino 2013, le gare dello sci alpino saranno ospitate dalla piste della Val di Fassa, in particolare la pista \u00abAloch\u00bb di Pozza di Fassa per lo Slalom e lo Slalom Gigante e la pista \u00abNuova Cima Uomo\u00bb del Passo San Pellegrino per la Discesa Libera e il SuperG.",
				"Uomini: Discesa libera, Super G, Slalom Gigante, Slalom, Combinata*\nDonne: Discesa libera, Super G, Slalom Gigante, Slalom, Combinata*\n*Classifica combinata basata sui risultati di almeno 3 eventi",
				"Ogni NUSF (Federazione Nazionale Sportiva Universitaria) pu\u00f2 schierare un massimo di 18 atleti per le gare di sci alpino, ma non \u00e8 possibile avere pi\u00f9 di 12 atleti dello stesso sesso. Inoltre, ogni gara prevede un massimo di 6 atleti appartenenti allo stesso paese.");
		x.setNome("sci alpino");
		x.setDescrizioneEn("The sports discipline that tries to the answer the question \u00abwho can make it down to the bottom of the mountain first?\u00bb One of the pillars of the sports programme of the Universiade, alpine skiing is the discipline with the highest level of participation at the event, with almost all the countries present at the Universiade usually entering at least one athlete in the downhill, super G, giant slalom and slalom events. These athletes also participate in the assigning of the medal for the \u00abcombined\u00bb event, which brings together results in at least three out of the four competitions. The first woman to win a gold medal in alpine skiing at the Universiade was C\u00e9cile Prince, who took the gold for France in the Super G organised on the slopes of Chamonix during the first edition of the Winter Universiade in 1960.\n\nAt the 2013 Winter Universiade in Trentino, the alpine skiing events will take place on ski runs in the Val di Fassa, specifically on the \u00abAloch\u00bb piste at Pozza di Fassa for the Slalom and Giant Slalom events and the \u00abNuova Cima Uomo\u00bb piste at Passo San Pellegrino for the Downhill and Super G events.");
		GPS[] listGps = new GPS[2];
		listGps[0] = new GPS(46.39306803994184, 11.799665411958777);
		listGps[0].setTitle("Passo San Pellegrino - Passo San Pellegrino");
		listGps[1] = new GPS(46.42895910089672, 11.695014369936438);
		listGps[1].setTitle("Pozza di Fassa - Ski Stadium Val di Fassa");

		x.setGeolocations(listGps);

		db.save(x);
		x = new SportObj(
				"Cross",
				1,
				"La combinata nordica \u00e8 stata uno dei pilastri fondamentali del programma sportivo dell\u2019Universiade, caratterizzandolo fin dalla sua prima edizione tenutasi a Chamonix in Francia nel 1960, nonostante alcune gare non siano state organizzate in un paio delle 25 edizioni delle Universiadi svoltesi fino a oggi.\n\nLa combinata nordica richiede la padronanza di due specialit\u00e0: lo sci di fondo e il salto con gli sci. I combinatisti sono ottimi saltatori e fortissimi fondisti che si sfidano sul trampolino e sulle piste di fondo, trasformando con un sistema particolare il distacco ottenuto in una o l\u2019altra gara in tempo o metri di ritardo. La tipica gara di combinata prevede prima una gara di salto con gli sci e poi, in base ai punti ottenuti, una gara di fondo con partenza \u00abGundersen\u00bb o a inseguimento, ovvero con il ritardo ottenuto nella gara precedente. Questo formato pu\u00f2 anche essere invertito, realizzando prima la gara di fondo con partenza in linea e poi quella di salto, trasformando in questo caso i secondi di ritardo registrati nella gara di fondo in punti (ovvero metri) di distacco per la gara di salto. Gli eventi di combinata nordica sono previsti solo per gli uomini, dal trampolino piccolo, sulla distanza di 10 km e con tre formati di gara: gundersen individuale, mass-start individuale e gara a squadre. Come nel caso del salto con gli sci, gli atleti sovietici, russi e giapponesi sono sempre stati tra i migliori interpreti di questa disciplina, anche se uno degli atleti di maggior successo internazionale e presente nell\u2019albo d\u2019oro delle Universiadi \u00e8 George Hettich (GER), vincitore di una medaglia d\u2019oro all\u2019Universiade del 2005 e campione olimpico in occasione dei Giochi Olimpici Invernali di Torino 2006.\n\nLe sedi delle gare di sci nordico saranno i trampolini e le piste della Val di Fiemme, una delle culle italiane dello sci nordico e gi\u00e0 sede di ben tre campionati del mondo (1991, 2003, 2013). Nel dettaglio, le gare di salto con gli sci si svolgeranno sul trampolino HS106 e HS134 di Predazzo, mentre le gare di sci di fondo si correranno sulle meravigliose piste iridate di Lago di Tesero.",
				"Uomini: Discesa libera, Super G, Slalom Gigante, Slalom, Combinata*\nDonne: Discesa libera, Super G, Slalom Gigante, Slalom, Combinata*\n*Classifica combinata basata sui risultati di almeno 3 eventi",
				"Ogni NUSF (Federazione Nazionale Sportiva Universitaria) può schierare un massimo di 18 atleti per le gare di sci alpino, ma non è possibile avere più di 12 atleti dello stesso sesso. Inoltre, ogni gara prevede un massimo di 6 atleti appartenenti allo stesso paese.");
		x.setNome("combinata nordica");
		x.setDescrizioneEn("In the case of Nordic skiing, the distances are not covered vertically, but rather horizontally. There are three Nordic skiing events: cross-country skiing, ski jumping and Nordic combined. The athletes will challenge each other over different distances or with different formats in each of these specialities. In the case of cross-country skiing, there are also two different styles: the \u00abclassic\u00bb style and the so-called \u00abfree style \u00bb or \u00abskating\u00bb technique.\n\nCross-country skiing has been one of the fundamental pillars of the sports programme of the Universiade since the very first edition held in Chamonix, France in 1960.\n\nCross-country skiing has gone from the 4 events provided for in 1960 to the 11 medal-winning events at this year\u2019s edition, with 5 competitions for men and women, in addition to a \u00abmixed\u00bb event. In the past Soviet and Russian athletes dominated this discipline, winning a very large number of medals on tracks all over the world. Of the medal-winners at the Universiade, one name that undoubtedly stands out is Justyna Kowalczyk, the Polish skier who went on to win several world and Olympic titles, as well as a large number of world cup competitions.\n\nThe cross-country skiing events will take place on the pistes of the Val di Fiemme, specifically the magnificent trails at Lake Tesero, one of the birthplaces of Italian cross-country skiing and which has already hosted no less than three World Championships (1991, 2003, 2013).");
		listGps = new GPS[2];
		listGps[0] = new GPS(46.282421123514105, 11.523825189299174);
		listGps[0].setTitle("Tesero - Lago di Tesero");
		listGps[0].setStreet("via Stazione 4");
		listGps[1] = new GPS(46.32887671502965, 11.601680676500745);
		listGps[1].setTitle("Predazzo - Ski Jumping Stadium");
		x.setGeolocations(listGps);

		db.save(x);
		x = new SportObj(
				"Curling",
				2,
				"Il modo pi\u00f9 facile per descrivere questa disciplina sicuramente \u00e8 quello di paragonarlo al gioco delle bocce, solo in versione decisamente pi\u00f9 invernale dato che viene giocato su un campo completamente ghiacciato.\n\nIn una partita di curling, due squadre composte da quattro giocatori lanciano delle pietre di granito di quasi 20 kg (dette stones) su una lastra di ghiaccio con l\u2019obiettivo di avvicinarle il pi\u00f9 possibile a un\u2019area di destinazione chiamata house e costituita da quattro anelli concentrici. Durante ogni intervallo di gioco, ovvero una mano, ogni squadra ha a disposizione otto stones, due per ogni giocatore. Una partita intera pu\u00f2 durare 8 o 10 mani. In ogni mano sono assegnati dei punti in base a quante stones della stessa squadra si trovano pi\u00f9 vicine al centro della house, esattamente come avviene nelle bocce. L\u2019obiettivo finale \u00e8 quello di conquistare pi\u00f9 punti della squadra avversaria.\n\nParticolarit\u00e0 di questo sport \u00e8 la cosiddetta fase di sweeping, utilizzata dai giocatori per riscaldare il ghiaccio con delle scope e modificare la traiettoria o la velocit\u00e0 della stone. Grandissima rilevanza ha anche la strategia assunta da ogni squadra che deve riuscire a proteggere le proprie stones da quelle avversarie posizionandole con ingegno e maestria nell\u2019area di house.\n\nLa prima apparizione del curling nel programma delle Universiadi avvenne a Tarvisio nel 2003, dove fu presentato come disciplina opzionale. Il successo fu immediato: nella prima edizione 6 squadre maschili e 5 squadre femminile battagliarono per l\u2019oro, attirando un buon numero di spettatori e risvegliando molto interesse.\n\nPer questi motivi, il curling \u00e8 diventato una degli sport obbligatori del programma delle Universiadi, registrando anno dopo anno la presenza di squadre di altissimo livello, in grado perfino di conquistare medaglie importanti in altre competizioni internazionali.\n\nDurante le Universiadi Invernali Trentino 2013, saranno organizzati due tornei di curling: uno femminile e uno maschile, con la presenza totale di 10 squadre cadauno.\n\nLa sede del torneo di curling sar\u00e0 lo spazioso Ice Rink di Baselga di Pin\u00e9, in grado di ospitare fino a 1800 spettatori che potranno inoltre dividersi tra le partite \u00abragionate\u00bb del curling e l\u2019emozione delle gare ad alta velocit\u00e0 del pattinaggio su ghiaccio, organizzate allo stadio del ghiaccio di Baselga di Pin\u00e9.",
				"Torneo femminile e torneo maschile",
				"Uomini: ogni torneo prevede la partecipazione di un massimo di 10 squadre, ognuna composta da 5 giocatori (quattro pi\u00f9 una riserva).\nDonne: ogni torneo prevede la partecipazione di un massimo di 10 squadre, ognuna composta da 5 giocatrici (quattro pi\u00f9 una riserva).\n\nOgni NUSF (Federazione Nazionale Sportiva Universitaria) potr\u00e0 chiedere di inserire una squadra maschile ed una femminile.\n\nIn caso siano iscritte pi\u00f9 squadre di quante previste, le squadre partecipanti saranno selezionate in base ai risultati conseguiti in altre edizioni delle Universiadi o i risultati di eventuali partite di qualificazione.");
		x.setNome("curling");
		x.setDescrizioneEn("The easiest way to describe this discipline is undoubtedly to compare it to the game of bowls, however in a decidedly more wintery version, given that it takes place on ice.\n\nIn a curling match, two teams made up of four players launch granite stones (stones) weighing almost 20 kg across a sheet of ice, with the objective of arriving as close as possible to the target, called the house, represented by four concentric rings. Each team has a total of eight stones available, two for each player, during each end, or set. A whole game may last 8 or 10 ends. The points for each end are awarded when all the players have launched their stones, on the basis of how many stones belonging to the same team are closer to the centre of the house, exactly as takes place in bowls. The final objective is to obtain more points than the opposing team.\n\nThe particular characteristic of this sport is the so-called sweeping phase, used by players to heat up the ice with their brooms in order to change the trajectory or the speed of the stone. The strategy adopted by the team is also very important, with each team trying to protect its own stones from those of the adversary by positioning them with ingenuity and expertise in the house area.\n\nCurling first appeared in the programme of the Universiade in Tarvisio in 2003, where it was presented as an optional discipline. It proved immediately popular: in the first edition 6 men\u2019s teams and 5 women\u2019s team battled it out for the gold medal, attracting a good number of spectators and giving rise to considerable interest.\n\nFor these reasons, curling has become one of the compulsory sports in the Universiade programme, with teams of the highest level participating year after year, also capable of winning important medals at other international competitions.\n\nDuring the 2013 Winter Universiade in Trentino, two curling tournaments will be organised: one for men and one for women, with a total of 10 teams in each.\n\nThe venue for the curling tournament will be the spacious ice rink at Baselga di Pin\u00e9, which can seat up to 1800 spectators, who will be able to follow both \u00abcalculated\u00bb curling matches and the excitement of speed skating competitions organised at Baselga di Pin\u00e9 ice rink.");
		listGps = new GPS[1];
		listGps[0] = new GPS(46.126572271845454, 11.251979685399577);
		listGps[0].setTitle("Ice Rink Piné Stadium");
		x.setGeolocations(listGps);
		db.save(x);

		x = new SportObj(
				"Figure",
				3,
				"La grazia e la potenza riuniti in uno sport, combinati con musica, ballo e in alcuni casi la capacit\u00e0 di eseguire tutti questi movimenti in perfetta sincronia in coppia: una vera e propria forma d\u2019arte.\n\nTutto questo \u00e8 il pattinaggio di figura, uno degli sport che solitamente riesce a riscuotere il maggior successo di pubblico dell\u2019Universiade, non solo grazie alle gare vere e proprie, ma anche grazie all\u2019esibizione prevista alla conclusione del programma sportivo dove la mancanza dello stress da competizione permette agli atleti di dimostrare pienamente il proprio potenziale, prendendosi magari anche qualche rischio in pi\u00f9 e regalando incredibili emozioni agli spettatori.\n\nIn occasione della prima Universiade, tenutasi nel 1960 a Chamonix in Francia, 6 uomini e 7 donne presero parte alle competizioni individuale di pattinaggio artistico e i primi due vincitori furono il francese Alain Calmat e la cecoslovacca Eva Grozajoeva. In totale, fino all\u2019edizione di quest\u2019anno, il programma di 23 Universiadi su 25 ha previsto delle gare di pattinaggio di figura.\n\nGrandi campioni e campionesse del pattinaggio di figura hanno partecipato e vinto importanti medaglie alle Universiadi, come la russa Irina Slutskaya o le coppie cinesi Zhang-Zhang e Shen-Zhao.\n\nDurante le Universiadi Invernali Trentino 2013, il programma di pattinaggio artistico prevede 4 eventi in cui saranno in palio importanti medaglie: prova maschile, prova femminile, prova a coppie e danza su ghiaccio.\n\nTutte queste gare saranno organizzate allo stadio Palaghiaccio di Trento, una costruzione in grado di ospitare pi\u00f9 di 1.030 persone e che risulter\u00e0 essere la cornice perfetta per delle gare che saranno sicuramente vere e proprie opere d\u2019arte.",
				"Individuale maschile, individuale femminile, danza su ghiaccio e coppie",
				"Individuale maschile: ogni NUSF (Federazione Nazionale Sportiva Universitaria) potr\u00e0 iscrivere un massimo di tre atleti\nIndividuale femminile: ogni NUSF (Federazione Nazionale Sportiva Universitaria) potr\u00e0 iscrivere un massimo di tre atlete\nCoppie: ogni NUSF (Federazione Nazionale Sportiva Universitaria) potr\u00e0 iscrivere un massimo di tre coppie\nDanza su ghiaccio: ogni paese potr\u00e0 iscrivere un massimo di tre coppie\nIn caso il numero di iscritti per le prove individuali maschili e femminili superi le 30 unit\u00e0, il comitato tecnico della FISU potrebbe decidere di ridurre il limite massimo per paese a due atleti e atlete. I vincitori di medaglie a Erzurum 2011 avranno la possibilit\u00e0 di partecipare alle gare senza essere considerati nella quota prevista per ogni paese.");
		x.setNome("pattinaggio artistico");
x.setDescrizioneEn("Grace and power united in one sport, combined with music, dance and in some cases the ability to carry out these movements in pairs in perfect synchrony: a genuine art form.\n\nThis is what figure skating is about, making it one of the sports that is generally most popular with the public of the Universiade, thanks not only to the competitions, but also to the final performance organised at the end of the sports programme. On this occasion the lack of stress linked to the competition allows the athletes to show off their full potential, perhaps taking a few extra risks and offering the spectators an incredible spectacle.\n\nAt the first Universiade, held in Chamonix, France in 1960, 6 men and 7 women took part in the individual figure skating competitions and the first two winners were the Frenchman Alain Calmat and the Czechoslovakian skater Eva Grozajoeva. In total, up to this year\u2019s edition, the figure skating competition for men and ladies has already been held 23 times out of 25 at the Winter Universiade.\n\nGreat figure skating champions have participated and won important medals at the Universiade, like the Russian skater Irina Slutskaya or the Chinese pairs Zhang-Zhang and Shen-Zhao.\n\nDuring the 2013 Winter Universiade in Trentino, the figure skating programme provides for 4 events, leading to the awarding of important medals: men\u2019s singles, ladies\u2019 singles, pairs and ice dance.\n\nAll these events will be held at the ice rink in Trento, a building seating more than 1,030 people, offering the perfect setting for competitions which will undoubtedly be authentic works of art.");
		listGps = new GPS[1];
		listGps[0] = new GPS(46.04093342207616, 11.122541427612305);
		listGps[0].setTitle("Trento - Ice Stadium");
		listGps[0].setStreet("Via Fersina (Loc. Ghiaie)");
		x.setGeolocations(listGps);
		db.save(x);
		x = new SportObj(
				"Freestyle",
				4,
				"Lo sci acrobatico o freestyle \u00e8 uno degli sport invernali pi\u00f9 giovani e ricalca pi\u00f9 o meno gli eventi di snowboard, praticandoli per\u00f2 con degli sci ai piedi piuttosto che con la tavola da snowboard.\n\nEssendo un sport in forte sviluppo e crescita soprattutto in ambiente universitario, il freestyle \u00e8 stato introdotto per la prima volta nel programma delle Universiadi durante l\u2019edizione austriaca di Innsbruck tenutasi nel 2005.\n\nAllora, si decise di presentare la specialit\u00e0 dello ski cross come disciplina dimostrativa, preparando delle apposite piste sulle quali gruppi di quattro o sei atleti si affrontarono per determinare chi fosse il pi\u00f9 veloce a scendere da un pendio caratterizzato da continui salti e ostacoli.\n\nIl successo di questo primo tentativo di introduzione conferm\u00f2 il free style come disciplina interessante per la FISU che decise di riproporre lo ski cross in un\u2019altra edizione delle Universiadi e di accompagnarlo con una nuova specialit\u00e0 freestyle (mogouls) in occasione di Erzurum 2011.\n\nAlle Universiadi Invernali Trentino 2013, il freestyle sar\u00e0 una delle due discipline facoltative scelte dagli organizzatori e le specialit\u00e0 presenti saranno due: ski cross e slope style.\n\nIn entrambi i casi, l\u2019obiettivo sar\u00e0 quello di scendere il pi\u00f9 rapidamente possibile da un pendio caratterizzato da salti impegnativi e da diversi altri ostacoli, ma con una principale differenza: nello ski cross gli atleti dovranno scendere in gruppi di quattro o sei, cercando quindi di evitare pericolosi contatti con gli avversari; mentre nello slope style un gruppo di giudici valuter\u00e0 con grandissima attenzione le acrobazie realizzate dagli sciatori durante la loro discesa a valle, premiando cos\u00ec i pi\u00f9 bravi e spettacolari.\n\nEsattamente come le gare di snowboard, anche quelle di freestyle si terranno sulle meravigliose piste del Monte Bondone, con la pista \u00abLavaman\u00bb teatro dello ski cross e dello slope style.",
				"Uomini: Ski cross, Slope style\nDonne: Ski cross, Slope styl",
				"Uomini: ogni NUSF (Federazione Nazionale Sportiva Universitaria) potr\u00e0 iscrivere un massimo di sei atleti, quattro dei quali potranno prendere parte alle singole gare.\nDonne: ogni NUSF (Federazione Nazionale Sportiva Universitaria) potr\u00e0 iscrivere un massimo di sei atlete, quattro delle quali potranno prendere parte alle singole gare.");
		x.setNome("sci acrobatico");
		x.setDescrizioneEn("Acrobatic or freestyle skiing is one of the youngest winter sports and more or less mirrors snowboarding events, but with the use of skis rather than a snowboard.\n\nAs it is a rapidly growing sport, especially in the university environment, freestyle skiing was introduced for the first time in the programme of the Universiade during the 2005 Austrian edition, held in Innsbruck.\n\nAt that time it was decided to present Ski Cross as a demonstrative discipline, preparing special courses, on which groups of four or six athletes competed in order to determine the fastest down a slope characterised by continuous jumps and obstacles.\n\nThe success of this first attempt to introduce the sport confirmed that freestyle skiing was a discipline of interest for FISU, which decided to offer Ski Cross again at another edition of the Universiade, accompanying it with a new freestyle skiing discipline (moguls) at Erzurum in 2011.\n\nAt the 2013 Winter Universiade in Trentino, freestyle skiing will be one of the optional disciplines chosen by the organisers and there will be two events: Ski Cross and Slopestyle.\n\nIn both cases the objective is to cover a course characterised by demanding jumps and various other obstacles as quickly as possible, but with one main difference: in Ski Cross the athletes must ski down in groups of four or six, attempting therefore to avoid dangerous contact with their adversaries, whereas in Slopestyle a group of judges careful assess the acrobatic moves of skiers during their descent, rewarding the best and most spectacular.\n\nAs takes place for the snowboarding competitions, the freestyle skiing events will also take place on the magnificent runs of Monte Bondone, with the \u00abLavaman\u00bb run acting as the venue for the Ski Cross and Slopestyle events.");
		listGps = new GPS[1];
		listGps[0] = new GPS(46.02759, 11.04461);
		listGps[0].setTitle("Monte Bondone - Monte Bondone");
		x.setGeolocations(listGps);

		db.save(x);
		x = new SportObj(
				"hockey",
				5,
				"Sport di squadra per eccellenza delle Universiadi, l\u2019hockey richiede atleti caratterizzati da forza, potenza, precisione e velocit\u00e0, oltre ad un fortissimo spirito di squadra.\n\nDisciplina di grandissimo successo in tutto il Nord America e in generale in quasi tutta Europa, l\u2019hockey \u00e8 considerato lo sport su ghiaccio pi\u00f9 conosciuto al mondo. Uno sport dove il contatto fisico tra i giocatori \u00e8 all\u2019ordine del giorno e garantisce partite emozionanti e senza quasi un attimo di respiro.\n\nNella storia delle Universiadi, il primo torneo di hockey fu organizzato nel 1962 durante la 2^ Universiade di Villars in Svizzera. Allora, quattro squadre presero parte al torneo maschile e la prima nazione a conquistare l\u2019oro fu la Cecoslovacchia. Dal 1962, l\u2019hockey \u00e8 stato presente nel programma delle Universiadi per ben 21 volte e a partire dall\u2019Universiadi del 2009 di Harbin (Cina) presenta anche il torneo femminile.\n\nIn occasione delle Universiadi di Erzurum in Turchia, ben 126 hockeiste provenienti da 6 paesi diversi si sono affrontate nel torneo femminile, dimostrando il successo di questo sport anche \u00abin rosa\u00bb.\n\nMoltissimi atleti che hanno preso parte alle Universiadi, hanno avuto modo di sfondare a livello internazionale, entrando a far parte di importanti squadre e conquistando grandi successi con le rispettive nazionali a Mondiali e Olimpiadi.\n\nDurante le Universiadi Invernali Trentino 2013, saranno organizzati i tornei femminile e maschile. Le partite del primo si svolgeranno nello stadio di Pergine Valsugana, mentre quelle del torneo maschile si svolgeranno negli stadi di Cavalese e Alba di Canazei.",
				"Torneo femminile e torneo maschile",
				"Uomini: il torneo riservato agli uomini prevede la partecipazione di un massimo di 12 squadre. Le squadre saranno accettate in base ai punteggi FISU e IIHF registrati al momento dell\u2019iscrizione. Uno dei posti nel torneo \u00e8 riservato alla squadra di casa (nel caso di Trentino 2013, la squadra italiana). Ogni squadra dovr\u00e0 essere composta da 20 giocatori e 2 portieri.\nDonne: il torneo riservato alle donne prevede la partecipazione di un massimo di 8 squadre. Le squadre accettate in base ai punteggi FISU e IIHF registrati al momento dell\u2019iscrizione sono risultate 6 avendo la squadra di casa espresso parere negativo alla partecipazione. Ogni squadra potr\u00e0 essere composta da un massimo di 20 giocatori e 2 portieri.");
		x.setNomeEn("hockey");
		x.setDescrizioneEn("The ultimate team sport at the Universiade, ice hockey demands force, power, precision and speed, as well as a very strong team spirit.\n\nA hugely popular discipline throughout North America and most of Europe, ice hockey is considered to be the best known sport on ice at global level. It is a sport where physical contact between the players is standard and guarantees exciting matches, with barely time to catch your breath.\n\nIn the history of the Universiade, the first hockey tournament was organised in 1962 during the 2nd Universiade in Villars, Switzerland. On that occasion four teams took part in the men\u2019s tournament and the first nation to win the gold medal was Czechoslovakia. Since 1962, ice hockey has been present in the programme of the Universiade no less than 21 times, and starting from the 2009 Universiade in Harbin (China) there has also been a women\u2019s tournament.\n\nAt the Universiade in Erzurum, Turkey, no less than 126 ice hockey players from 6 different countries participated in the women\u2019s tournament, demonstrating the success of this sport also among women.\n\nA large number of athletes participating at the Universiade have gone on to have successful careers at international level, joining important teams and achieving major success with their respective national teams at World Championships and the Olympics.\n\nDuring the 2013 Winter Universiade in Trentino, both women\u2019s and men\u2019s tournaments will be organised. The matches of the former will take place at the ice rink in Pergine Valsugana, whereas the men\u2019s tournament will take place at the rinks in Cavalese and Alba di Canazei.");
		listGps = new GPS[3];
		listGps[0] = new GPS(46.46179584266813, 11.784283101244108);
		listGps[0].setTitle("Alba di Canazei - Gianmario Scola Ice Hockey Arena");
		listGps[1] = new GPS(46.07192313475388, 11.235533631051503);
		listGps[1].setTitle("Pergine Valsugana - Ice Stadium");
		listGps[2] = new GPS(46.28583945210038, 11.464570111721242);
		listGps[2].setTitle("Cavalese - Municipal Ice Arena");
		x.setGeolocations(listGps);
		db.save(x);
		x = new SportObj(
				"Nordic",
				6,
				"Nel caso dello sci nordico, le distanze non sono percorse in verticale, ma piuttosto in orizzontale. Tre sono le specialit\u00e0 dello sci nordico: sci di fondo, salto con gli sci e combinata nordica. In ognuna di queste specialit\u00e0, gli atleti si sfidano su distanza o formati di gara diversi. Nel caso dello sci di fondo, si cambia anche stile, passando da quello \u00abclassico\u00bb al cosiddetto \u00abstile libero\u00bb o \u00abskating\u00bb\n\nLo sci di fondo \u00e8 stato uno dei pilastri fondamentali del programma sportivo dell\u2019Universiade, caratterizzandolo fin dalla sua prima edizione tenutasi a Chamonix in Francia nel 1960.\n\nLo sci di fondo \u00e8 passato dalle 4 gare previste nel 1960 agli 11 eventi medagliati dell\u2019edizione di quest\u2019anno, con 5 gare per uomini e donne, oltre che una gara \u00abmista\u00bb. In passato, gli atleti sovietici e russi sono stati i grandi dominatori di questa disciplina, conquistando moltissime medaglie sulle piste di tutto il mondo. Tra i nomi dei vincitori di medaglie alle Universiadi, quello che spicca pi\u00f9 di tutti \u00e8 sicuramente quello della polacca Justyna Kowalczyk, gi\u00e0 vincitrice di diversi titoli mondiali e olimpici oltre che di moltissime gare di coppa del mondo.\n\nLe sedi delle gare di sci di fondo saranno le piste della Val di Fiemme ed in particolare sulle meravigliose piste iridate di Lago di Tesero, una delle culle italiane e gi\u00e0 se",
				"Uomini: 10 km individuale TL, 15 km Skiathlon (TC+TL), Sprint TC, 30 km partenza in linea TC, staffetta 4x10 km (TC-TC-TL-TL)\nDonne: 5 km individuale TL, 10 km Skiathlon (TC+TL), Sprint TC, 15 km partenza in linea TC, staffetta 3x5 km (TC-TL-TL)\nMiste: Staffetta sprint",
				"Uomini: ogni NUSF (Federazione Nazionale Sportiva Universitaria) pu\u00f2 iscrivere un massimo di 8 concorrenti, 6 dei quali potranno partecipare alle gare individuali e 4 dei quali parteciperanno alla staffetta.\nDonne:ogni NUSF (Federazione Nazionale Sportiva Universitaria) pu\u00f2 iscrivere un massimo di 8 concorrenti, 6 dei quali potranno partecipare alle gare individuali e 3 dei quali parteciperanno alla staffetta.\nLa staffetta mista \u00e8 composta da due atleti, un uomo e una donna. Alla staffetta mista, ogni NUSF (Federazione Nazionale Sportiva Universitaria) potr\u00e0 iscrivere un massimo di due squadre.\n\n ");
		x.setNome("sci nordico");
		x.setDescrizioneEn("Nordic Combined has been one of the fundamental pillars of the sports programme of the Universiade, characterising it from the very first edition held in Chamonix, France in 1960, although some competitions have not been organised on a couple of occasions in the 25 editions of the Universiade held to date.\n\nNordic Combined requires skills in two different disciplines: ski jumping and cross-country skiing. Competitors are excellent ski jumpers and cross-country skiers who challenge each other on ski jumping hills and cross-country tracks, transforming the gap obtained in one competition or the other into time or metres . A typical Nordic Combined event provides for a ski jumping competition and then, on the basis of the points obtained, a cross- country skiing race with \u00abGundersen\u00bb departure, i.e. with the delay accumulated in the previous competition. This format may also be inverted, by having the cross- country skiing race first, with a mass-start departure followed by the ski jumping competition, in this case transforming the seconds\u2019 delay recorded in the cross-country skiing race into points (or rather metres) in the ski jumping event. Nordic Combined events are only organised for men, with normal hill ski jumping, races over a distance of 10 km and three competition formats: individual Gundersen, individual mass-start and a team event. As in the case of ski jumping, Soviet, Russian and Japanese athletes have always been among the best in this discipline, although one of the most successful international athletes present in the list of gold medallists at the Universiade is George Hettich (GER), winner of a Gold Medal at the 2005 Universiade and Olympic champion at the Winter Olympics in Turin in 2006.\n\nThe venues for the Nordic combined events will be the hills and tracks of the Val di Fiemme, one of the birthplaces of Nordic skiing in Italy, which has already hosted no less than three World Championships (1991, 2003, 2013). Specifically, the ski jumping events will take place on the HS106 and HS134 hills at Predazzo, whereas the cross-country skiing races will take place on the magnificent tracks at Lake Tesero.");
		listGps = new GPS[1];
		listGps[0] = new GPS(46.282421123514105, 11.523825189299174);
		listGps[0].setTitle("Tesero - Lago di Tesero");
		listGps[0].setStreet("via Stazione 4");
		x.setGeolocations(listGps);
		db.save(x);
		x = new SportObj(
				"Shorttracking",
				7,
				"Una specie di \u00abfratello minore\u00bb del pattinaggio di velocit\u00e0 su ghiaccio, lo short track si differenzia dal proprio \u00abfratellone\u00bb per due principali motivi: innanzitutto si svolge su piste di 111,12 metri ed all\u2019interno della pista di ghiaccio 30x60m e in secondo luogo prevede che gli atleti si affrontino in gruppi o batterie di 4 o 8 concorrenti, riducendo di molto i margini di manovra dei pattinatori. Per questo, lo short track \u00e8 caratterizzato da altissime velocit\u00e0 e soprattutto da una lotta corpo a corpo tra gli atleti per prendere la testa della corsa e tagliare per primo il traguardo.\n\nL\u2019agilit\u00e0, la potenza e la velocit\u00e0 richieste in questo sport, oltre alla necessit\u00e0 di calcolare bene la tattica di gara, rendono lo short track una delle discipline pi\u00f9 emozionanti di tutto il programma delle Universiadi, con gare incerte fino all\u2019ultimo millimetro e distacchi minimi che possono fare la differenza tra la medaglia d\u2019oro e il quarto posto.\n\nLo short track fu introdotto per la prima volta nel programma delle Universiadi nel 1985, durante l\u2019edizione di Belluno. Allora, 10 squadre maschili e 9 squadre femminili presero parte alle competizioni, per un totale di 58 atleti. Le squadre pi\u00f9 forti furono fin da subito quella canadese e quella statunitense, portando a casa diversi ori.\n\nOggi per\u00f2 il vento sembra essere cambiato e gli atleti pi\u00f9 forti provengono quasi tutti dai paesi asiatici (Corea del Sud, Giappone e Cina). Molti atleti di short track vincitori di medaglie alle Universiadi hanno conquistato anche importanti titoli olimpici o mondiali. Tra di loro, si possono trovare i nomi delle due cinesi omonime Yang Yang (A) e Yang Yang (S), della coreana Min-Kyung Choi o dell\u2019italiana Marta Capurso.\n\nDurante le Universiadi Invernali Trentino 2013, le medaglie d\u2019oro in palio saranno otto, con sei gare individuali e due staffette. La sede delle gare di short track sar\u00e0 la stessa di quelle di pattinaggio di figura, ovvero al Palaghiaccio di Trento.",
				"Uomini: 500 m, 1000 m, 1500 m, staffetta 5000 m\nDonne: 500 m, 1000 m, 1500 m, staffetta 3000 m",
				"Ogni NUSF (Federazione Nazionale Sportiva Universitaria) potr\u00e0 iscrivere 6 atleti e 6 atlete per le gare individuali, ma non pi\u00f9 di 3 atleti e 3 atlete potranno partecipare a ogni gara. Se dovesse essere necessario, per motivi organizzativi, il numero di partecipanti potrebbe essere ridotto.\nPer le staffette, ogni paese potr\u00e0 iscrivere una squadra composta da 4 atleti, pi\u00f9 una riserva.\u2003");
		x.setNome("pattinaggio");
x.setDescrizioneEn("A sort of \u00abyounger brother\u00bb of speed skating on ice, short track speed skating differs from its \u00abbig brother\u00bb in two main ways: first of all it takes place on a 111.12 metre track inside a 30x60m ice rink, and secondly it involves the athletes competing with each other in groups or heats of 4 or 8 competitors, reducing skaters\u2019 room for manoeuvre considerably. For this reason, short track speed skating is characterised by its very high speed and above all by the fight between athletes to get in front and make it to the finishing line first.\n\nThe agility, power and speed required for this sport, along with the need to calculate competition tactics carefully, make short track speed skating one of the most exciting disciplines in the whole Universiade programme, with the result being uncertain until the very last moment and minimal gaps in time that can represent the difference between the gold medal and fourth place.\n\nShort track speed skating was introduced to the programme of the Universiade for the first time in 1985, during the Belluno edition. On that occasion, 10 men\u2019s teams and 9 women\u2019s teams took part in the events, with a total of 58 athletes. The strongest teams from the beginning were the Canadians and the Americans, who took home several gold medals.\n\nToday however the wind seems to have changed, and the strongest athletes almost all come from Asiatic countries (South Korea, Japan and China). Many short track speed skating athletes winning medals at the Universiade have also won important Olympic and world titles. Among them, we can find the names of two Chinese skaters with the same name Yang Yang (A) and Yang Yang (S), the Korean skater Min-Kyung Choi and the Italian skater Marta Capurso.\n\nAt the 2013 Winter Universiade in Trentino the athletes will compete for eight gold medals, with six individual events and two relays. The venue for the short track speed skating events will be the same as for the figure skating competitions, namely Trento Ice Rink.");
		listGps = new GPS[1];
		listGps[0] = new GPS(46.04093342207616, 11.122541427612305);
		listGps[0].setTitle("Trento - Ice Stadium");
		listGps[0].setStreet("Via Fersina (Loc. Ghiaie)");
		x.setGeolocations(listGps);
		db.save(x);
		x = new SportObj(
				"Ski Jumping",
				8,
				"Assieme allo sci di fondo e alla combinata nordica, il salto con gli sci \u00e8 stato uno dei pilastri fondamentali del programma sportivo dell\u2019Universiade fin dalla sua prima edizione tenutasi a Chamonix in Francia nel 1960, nonostante le gare di combinata nordica e quelle di salto non siano state organizzate in un paio delle 25 edizioni delle Universiadi svoltesi fino a oggi.\n\nIl salto con gli sci ha assunto una posizione crescente nel programma delle Universiadi soprattutto grazie alla sua spettacolarit\u00e0 e al grande seguito che riscuote tra gli appassionati di sport invernali. Le prime gare di salto con gli sci delle Universiadi videro la partecipazioni di 16 atleti uomini provenienti da 7 paesi, con solo una gara in programma: quella dal trampolino piccolo. Da allora molte cose sono cambiate e oggi il programma delle Universiadi prevede ben cinque gare: tre per gli uomini (trampolino piccolo, trampolino grande e gara a squadre), una riservata alle donne (trampolino piccolo) e una a squadre miste. Gli storici dominatori delle gare di questa disciplina sono stati gli atleti sovietici, russi, sloveni e giapponesi.\n\nLe gare di salto con gli sci si svolgeranno sul trampolino HS106 e HS134 di Predazzo.",
				"Uomini: HS134 individuale - HS106 a squadre\nDonne: HS106 individuale\nMista (1 uomo + 1 donna): HS106",
				"Ogni NUSF (Federazione Nazionale Sportiva Universitaria) pu\u00f2 iscrivere un massimo di 8 atleti, 6 dei quali potranno partecipare alle gare individuali. La gara a squadre maschile dal trampolino grande richiede la partecipazione di squadre formate da 3 atleti ed \u00e8 previsto un massimo di una squadra per paese. La gara a squadre miste richiede la partecipazione di squadre formate da 2 atleti, un uomo e una donna, ed \u00e8 previsto un massimo di due squadre per paese");
		x.setNome("salto");
		x.setDescrizioneEn("Together with cross-country skiing and Nordic combined, ski jumping has been one of the fundamental pillars of the sports programme of the Universiade since the very first edition held in Chamonix, France in 1960, although the Nordic combined and ski jumping events have not been organised on a couple of occasions in the 25 editions of the Universiade held to date.\n\nSki jumping has taken on increasing importance in the programme of the Universiade thanks above all to its spectacular nature and its popularity among winter sports enthusiasts. The first ski jumping competitions at the Universiade saw the participation of 16 male athletes from 7 countries, with just one event scheduled: normal hill. Since then many things have changed and today the programme of the Universiade provides for no less than five events: three for men (normal hill, large hill and a team event), one reserved for women (normal hill) and one for mixed teams. Historically, this event has been dominated by Soviet, Russian, Slovenian and Japanese athletes.\n\nThe ski jumping events will take place on the HS106 and HS134 hills at Predazzo.");
		listGps = new GPS[1];
		listGps[0] = new GPS(46.32887671502965, 11.601680676500745);
		listGps[0].setTitle("Predazzo - Ski Jumping Stadium");
		x.setGeolocations(listGps);
		db.save(x);
		x = new SportObj(
				"Snowboarding",
				9,
				"Una delle discipline pi\u00f9 giovani del programma delle Universiadi, lo snowboard fu introdotto nel 1995 durante le Universiadi di Jaca in Spagna. Inizialmente fu considerato solo uno sport dimostrativo e 29 atleti in rappresentanza di 10 Paesi presero parte alle prime gare di snowboard di Jaca.\n\nIl grandissimo livello di spettacolarit\u00e0 della disciplina e la sua diffusione tra gli ambienti universitari gli permise per\u00f2 rapidamente di conquistare sempre pi\u00f9 spazio e ben presto lo snowboard divenne una delle discipline obbligatorie del programma, introducendo a partire dalle Universiadi del 1999 organizzate a Poprad-Tatry in Slovacchia i salti e l\u2019emozione del \u00abborder cross\u00bb. Pi\u00f9 tardi la specialit\u00e0 cambi\u00f2 nome, diventando Snowboard cross, ed entrarono a far parte del programma anche l\u2019halfpipe e lo slope style, specialit\u00e0 incredibilmente spettacolari.\n\nLo slope style \u00e8 un formato di gara che doveva realizzare il proprio debutto in occasione delle Universiadi di Erzurum nel 2011, ma fu annullata per le condizioni di vento instabili. L\u2019Universiade Invernale Trentino 2013 segner\u00e0 quindi il debutto ufficiale di questa specialit\u00e0 nel programma delle Universiadi.\n\nOltre a questa specialit\u00e0, il programma dell\u2019Universiade Invernale Trentino 2013 prevede anche gli eventi dello slalom gigante parallelo, dell\u2019halfpipe e dello snowboard cross, sia per uomini sia per donne.\n\nNello slalom gigante parallelo e nello snowboard cross sar\u00e0 il tempo a stabilire un vincitore, con gare caratterizzate da emozionanti sfide \u00abcorpo a corpo\u00bb incerte fino all\u2019ultimo.\n\nNell\u2019halfpipe e nello slope style invece, oltre al tempo, saranno le acrobazie degli atleti a fare la differenza, con salti e \u00abtrick\u00bb che verranno valutati attentamente da una giuria e risulteranno essere quindi l\u2019elemento chiave per la conquista di una medaglia.\n\nLa sede ospitante delle gare di snowboard sar\u00e0 il Monte Bondone, mettendo in mostra il meglio delle sue piste e del suo nuovo halfpipe e snowpark. In particolare, la gara del gigante parallelo si svolger\u00e0 sulla pista Canalon, quella di Snowboard cross sulla spettacolare discesa del \u00abLavaman\u00bb, mentre l\u2019halfpipe e lo slope style occuperanno il bellissimo \u00abSnow Park Monte Bondone\u00bb.",
				"Uomini e donne: Slalom gigante parallelo, Halfpipe, Snowboard cross, Slope style",
				"Uomini: ogni NUSF (Federazione Nazionale Sportiva Universitaria) potr\u00e0 iscrivere un massimo di 10 atleti, dei quali solo 4 potranno prendere parte a ogni evento in programma.\nDonne: ogni NUSF (Federazione Nazionale Sportiva Universitaria) potr\u00e0 iscrivere un massimo di 8 atlete, delle quali solo 4 potranno prendere parte a ogni evento in programma.");
		x.setNome("snowboard");
		x.setDescrizioneEn("One of the younger disciplines in the programme of the Universiade, snowboarding was introduced at the 1995 Universiade in Jaca, Spain. Initially it was considered only as a demonstration sport and 29 athletes representing 10 countries took part in the first snowboarding competitions in Jaca.\n\nHowever, the spectacular nature of the sport and its popularity in the university environment rapidly allowed it to conquer more space, and snowboarding soon became one of the compulsory disciplines in the programme, introducing the jumps and excitement of \u00abborder cross\u00bb starting from the 1999 Universiade organised in Poprad-Tatry, Slovakia. Later the event changed its name, becoming Snowboard Cross, while the Half Pipe and Slope Style events, incredibly spectacular to watch, also became a part of the programme.\n\nSlope Style is an event that was supposed to make its debut at the Universiade in Erzurum in 2011, but it was cancelled due to windy conditions. The 2013 Winter Universiade in Trentino will therefore mark the official debut of this speciality in the programme of the Universiade.\n\nIn addition to this event, the programme of the 2013 Winter Universiade in Trentino also includes parallel giant slalom, half pipe and snowboard cross competitions, for both men and women.\n\nIn the parallel giant slalom and snowboard cross events the winner will be established on the basis of the time, with events characterised by exciting \u00abone on one\u00bb races, uncertain until the end.\n\nIn the half pipe and slope style events on the other hand, it will be the acrobatic moves of the athletes that make the difference, with jumps and \u00abtricks\u00bb that will be carefully assessed by a jury and which will thus represent the key element in winning a medal.\n\nThe snowboarding competitions will take place on Monte Bondone, showing off its best runs, along with the new halfpipe and snowpark. Specifically, the parallel giant slalom will take place on the Canalon piste and the snowboard cross event on the spectacular \u00abLavaman\u00bb run, while the magnificent \u00abMonte Bondone Snow Park\u00bb will act as the venue for the half pipe and slope style events.");
		listGps = new GPS[1];
		listGps[0] = new GPS(46.02759, 11.04461);
		listGps[0].setTitle("Monte Bondone - Monte Bondone");
		x.setGeolocations(listGps);
		db.save(x);
		x = new SportObj(
				"SpeedSkating",
				10,
				"Il pattinaggio di velocit\u00e0 prevede all\u2019interno del proprio programma delle competizioni su distanze brevi, adatte a pattinatori di grande potenza, e competizioni su distanze pi\u00f9 lunghe, adatte a pattinatori di maggiore resistenza.\n\nIn questo sport, gli atleti sono lasciati soli contro il cronometro, anche se solitamente hanno la possibilit\u00e0 di pattinare assieme a uno dei loro avversari, partendo per\u00f2 da lati opposti della pista lunga 400 metri. Inutile dire che il vincitore \u00e8 colui che riesce a segnare il miglior tempo sulla distanza prevista.\n\nIl pattinaggio di velocit\u00e0 su ghiaccio \u00e8 una delle due discipline facoltative inserite nel programma delle Universiadi di Trentino 2013, nonostante possa vantare una lunga storia all\u2019interno del programma di questa manifestazione.\n\nLa prima volta che il pattinaggio di velocit\u00e0 compar\u00ec in un programma sportivo delle Universiadi fu nel 1968 in occasione delle Universiadi di Innsbruck in Austria, presentando per\u00f2 gare destinate solo a pattinatori uomini. A partire dall\u2019edizione seguente (1970), furono organizzate anche gare per donne.\n\nIn totale, il pattinaggio di velocit\u00e0 su ghiaccio \u00e8 stato presente nel programma di otto Universiadi, registrando la vittoria e la partecipazione di grandissimi campioni vincitori anche di medaglie olimpiche e mondiali.\n\nTra i pi\u00f9 importanti, si ricordano i nomi dei coreani Lee Kang Seok e Sang Lee Hwa, del tedesco Erhard Keller e del russo Aleksander Zhekulayev, ma soprattutto quelli dei campioni olimpici e italiani Enrico Fabris e Matteo Anesi.\n\nAnesi pu\u00f2 anche essere considerato un \u00abprodotto\u00bb della pista dove si svolgeranno le gare di pattinaggio di velocit\u00e0 su ghiaccio, ovvero quella di Baselga di Pin\u00e9, dato che fin da piccolo si \u00e8 allenato proprio in questa struttura, equipaggiata di anello olimpico da 400 metri e gi\u00e0 sede di diversi appuntamenti di coppa del mondo e mondiali allround.",
				"Uomini: 500m, 1000m, 1500m, 5000m, 10000m, gara a inseguimento a squadre\nDonne: 500m, 1000m, 1500m, 3000m, 5000m, gara a inseguimento a squadre",
				"Ogni NUSF (Federazione Nazionale Sportiva Universitaria) potr\u00e0 iscrivere un massimo di 24 atleti, 12 uomini e 12 donne.\nPer quello che riguarda gli uomini, ogni NUSF (Federazione Nazionale Sportiva Universitaria) potr\u00e0 iscrivere 5 atleti per ogni distanza, ma non pi\u00f9 di quattro di essi potranno prendere parte alle distanze dei 500m, 1000m e 1500m; mentre tre di essi potranno prendere parte alle distanze dei 5000m e 10000m. Se necessario, il numero di concorrenti potrebbe essere ridotto.\nPer quello che riguarda le donne, ogni NUSF (Federazione Nazionale Sportiva Universitaria) potr\u00e0 iscrivere 5 atleti per ogni distanza, ma non pi\u00f9 di quattro di essi potranno prendere parte alle distanze dei 500m, 1000m e 1500m; mentre tre di essi potranno prendere parte alle distanze dei 3000m e 5000m. Se necessario, il numero di concorrenti potrebbe essere ridotto.\nSulle distanze dei 3000m femminili e 5000m maschili, sar\u00e0 accettato un massimo di 32 atleti per ogni evento; mentre sulle distanze dei 5000m femminili e 10000m maschili, sar\u00e0 accettato un massimo di 16 atleti per ogni evento.\n\nPer la gara a inseguimento a squadre, sar\u00e0 accettato un numero massimo di 10 squadre nazionali (uomini e donne). Ogni squadra dovr\u00e0 essere composta da quattro atleti, tre dei quali prenderanno parte alla gara. Le squadre si qualificheranno in base ai risultati del secondo miglior pattinatore della squadra, considerando il tempo fatto segnare nella gara dei 3000m per le donne e i 5000m per gli uomini.");
		x.setNome("pattinaggio");
		x.setDescrizioneEn("Speed skating competitions provide for events over short distances, suitable for more powerful skaters, and over longer distances, suitable for skaters with greater resistance.\n\nIn this sport, the athletes are alone against the stop-watch, although they usually have the chance to skate together with one of their adversaries, albeit starting from opposite ends of a 400 metre track. It need hardly be said that the winner is the competitor achieving the best time over the relevant distance.\n\nSpeed skating on ice is one of the two optional disciplines included in the programme of the 2013 Winter Universiade in Trentino, although it can boast a long history within the programme of the event.\n\nThe first time that speed skating appeared in the Universiade sports programme was in 1968, during the Universiade in Innsbruck, Austria, although with competitions for male skaters alone. Starting from the subsequent edition (1970), women\u2019s competitions were also organised.\n\nIn total, speed skating on ice has been included in eight Universiades, seeing the victory and participation of great champions also winning Olympic and World Championship medals.\n\nThe most important names include the Korean skaters Lee Kang Seok and Sang Lee Hwa, the German Erhard Keller and the Russian Aleksander Zhekulayev, but above all the Olympic and Italian champions Enrico Fabris and Matteo Anesi.\n\nAnesi can also be considered a \u00abproduct\u00bb of the track where the speed skating events will take place, the Baselga di Pin\u00e9 ice rink, given that he has trained there since he was a child. It has an Olympic 400 metre track and has already hosted several World Cups and World All-Round Speed Skating Championships.");
		listGps = new GPS[1];
		listGps[0] = new GPS(46.126572271845454, 11.251979685399577);
		listGps[0].setTitle("Ice Rink Piné Stadium");
		x.setGeolocations(listGps);
		db.save(x);
		x = new SportObj(
				"Biathlon",
				11,
				"Lo sport che coniuga lo sci di fondo con la precisione del tiro a segno, creando una combinazione appassionante che richiede agli atleti di gestire al meglio le forze in pista per \u00abcoprire\u00bb tutti i bersagli al poligono.\n\nUn errore pu\u00f2 costare caro: nei formati di gara pi\u00f9 comuni ad ogni errore corrisponde un giro di penalit\u00e0 di 150 metri, mentre in altri eventi pu\u00f2 arrivare addirittura a un minuto di penalit\u00e0 sul tempo finale. Per quello che riguarda lo sci di fondo, agli atleti \u00e8 richiesto di sciare in tecnica libera, lo stile sicuramente pi\u00f9 adatto per trasportare sulle spalle una carabina calibro .22 LR del peso minimo di 3,5 kg.\n\nNata come disciplina di sopravvivenza nei paesi nordici, la diffusione del biathlon \u00e8 andata in crescendo negli ultimi anni, ottenendo un successo incredibile in moltissimi paesi e conquistando i cuori di tutti gli appassionati degli sport invernali.\n\nIl debutto di questa disciplina alle Universiadi avvenne nel 1983, a Sofia in Bulgaria. In questa prima occasione, 7 paesi e 34 atleti si schierarono ai nastri di partenza e con il \u00abfucile in spalla\u00bb per prendere parte alle prime gare universitarie di biathlon. Un po\u2019 come avvenuto in altre discipline, gli atleti sovietici e dell\u2019Est Europa sono stati per molto tempo tra i migliori interpreti di questo sport, facendola da padroni per diversi anni. A partire da Harbin in Cina nel 2009, la staffetta mista entr\u00f2 a far parte del programma delle Universiadi, permettendo cos\u00ec di aumentare il numero di paesi partecipanti.\n\nMolti sono i nomi di importanti atleti che hanno avuto modo di partecipare a un\u2019Universiade prima di conquistare medaglie importanti per i rispettivi paesi: Olga Zaytseva, Thomas Sikora e Olga Nazareva sono solo alcuni esempi.\n\nDurante le Universiadi Invernali Trentino 2013 saranno ben 9 gli eventi medagliati nel programma di gara, quattro divisi per uomini e donne e una staffetta mista.\n\nLe gare di biathlon saranno organizzate sulle piste del Lago di Tesero che, dopo aver ormai raggiunto grandissima fama come sede di gare di sci di fondo, punta a conquistare i cuori degli appassionati del biathlon. Il nuovissimo poligono del Lago di Tesero e le sue piste risulteranno essere quindi un meraviglioso teatro per le gare di biathlon, andando cos\u00ec a combinarsi perfettamente nel calendario con le gare di sci nordico programmate in Val di Fiemme.",
				"Uomini: Individuale (20 km), Sprint (10 km), Inseguimento (12,5 km), Mass-start (15 km)\nDonne: Individuale (15 km), Sprint (7,5 km), Inseguimento (10 km), Mass-start (12,5 km)\nStaffetta mista 2x6 km (donne) + 2x7,5 km (uomini)",
				"Ogni NUSF (Federazione Nazionale Sportiva Universitaria) pu\u00f2 iscrivere un massimo di 16 atleti (8 uomini e 8 donne). Di questi, solo 12 (6 uomini e 6 donne) potranno prendere parte alle gare individuali e sprint.\n\nAlla gara a inseguimento potranno partecipare solo gli atleti o le atlete che termineranno la gara sprint nelle prime 60 posizioni. La partenza avviene con il vincitore dello sprint per primo e gli atleti a seguire con il distacco accumulato nello sprint.\n\nNella mass-start invece saranno disponibili solo 30 posti di partenza e quindi potranno partecipare solo i vincitori di una medaglia nelle altre gare e coloro che riusciranno a ottenere il punteggio pi\u00f9 alto seguendo il sistema di punteggio della Federazione Internazionale di Biathlon (IBU) e basandosi sui risultati delle tre gare precedenti.\n\nNella staffetta mista, ogni paese potr\u00e0 iscrivere un massimo di una squadra composta da due donne e due uomini.");
		x.setNome("Biathlon");
		x.setDescrizioneEn("A sport that combines cross-country skiing with precision shooting, creating an exciting mix demanding that athletes conserve their energy on the track in order to hit all the targets at the shooting range.\n\nMistakes can be costly: in the most common competition formats each error corresponds with a penalty loop of 150 metres, whereas in other events there may be up to a minute\u2019s penalty on the final time. As regards the skiing technique, the athletes are required to ski using the skate technique, undoubtedly the most suitable while carrying a .22 calibre long rifle weighing a minimum of 3.5 kg.\n\nDeveloped as a survival discipline in Nordic countries, the biathlon has become increasingly popular in the last few years, proving very successful in a large number of countries and winning over winter sports enthusiasts.\n\nThe discipline made its debut at the Universiade in 1983, in Sofia, Bulgaria. On that occasion, 7 countries and 34 athletes set off with their \u00abrifles on their backs \u00bb to take part in the first university biathlon competitions. As took place in many other disciplines, for many years Soviet and Eastern European athletes dominated in this sport. The mixed relay became a part of the Universiade programme starting from Harbin in China in 2009, thus giving countries with fewer competitors more opportunities to participate.\n\nMany important athletes have competed at the Universiade before going on to win important medals for their respective countries: Olga Zaytseva, Thomas Sikora and Olga Nazareva are just some of the examples.\n\nDuring the 2013 Winter Universiade there will be no less than 9 medal-winning events in the competition programme, four separate competitions for men and women and a mixed relay.\n\nThe biathlon competitions will be organised at the Lake Tesero centre. After having become very well-known as the home of cross-country skiing competitions, it now hopes to win over biathlon enthusiasts. The brand new shooting range at Lake Tesero and the cross-country skiing tracks will therefore be a marvellous setting for the biathlon competitions, fitting in perfectly with Nordic skiing competitions scheduled in the Val di Fiemme.");
		
		listGps = new GPS[1];
		listGps[0] = new GPS(46.282421123514105, 11.523825189299174);
		listGps[0].setTitle("Tesero - Lago di Tesero");
		listGps[0].setStreet("via Stazione 4");
		x.setGeolocations(listGps);

		db.save(x);
	}

	@RequestMapping(method = RequestMethod.GET, value = "/sport")
	public @ResponseBody
	List<SportObj> getAllSport(HttpServletRequest request,
			HttpServletResponse response, HttpSession session) {

		return db.findAll(SportObj.class);
	}

	@RequestMapping(method = RequestMethod.POST, value = "/sport/search")
	public @ResponseBody
	List<SportObj> searchSport(HttpServletRequest request,
			HttpServletResponse response, HttpSession session,
			@RequestBody Domanda domanda) throws IOException {

		String faq = domanda.getNome();
		faq = faq.toLowerCase();
		faq = faq.replace("%27", " ");
		faq = faq.replace("+", " ");
		faq = faq.replace("=", "");
		faq = faq.replace("%3B", " ");
		faq = faq.replace("%2C", " ");
		faq = faq.replace(".", " ");
		faq = faq.replace("%21", " ");
		faq = faq.replace("è", "�");
		faq = faq.replaceAll("\\s+$", "");
		faq = faq.replace("  ", " ");
		
		Map<String,String> mapMatch=new HashMap<String, String>();
		mapMatch.put("sci alpino","Alpine");
		mapMatch.put("salto","Ski Jumping");
		//mapMatch.put("pattinaggio","Speed Skating");
		//mapMatch.put("pattinaggio","Shorttracking");
		mapMatch.put("hockey","Ice");
		mapMatch.put("curling","Curling");
		mapMatch.put("biathlon","Biathlon");
		mapMatch.put("snowboard","Snowboarding");
		mapMatch.put("combinata nordica","Nordic");
		mapMatch.put("freestyle","Freestyle");

		
		if(mapMatch.containsKey(faq)){
			return getSportMatchFromDb(mapMatch.get(faq));
		}else{
			
			return getSportMatchFromDb(faq);
		}
		
		

	}

	public List<SportObj> getSportMatchFromDb(String pattern) {
		Query query6 = new Query();
		query6.addCriteria(Criteria.where("descrizione").regex(pattern, "i"));
		//query6.addCriteria(Criteria.where("descrizione").regex(pattern, "i"));
		
		List<SportObj> ret=db.find(query6, SportObj.class);
		if(ret.isEmpty()){
			query6 = new Query();
			query6.addCriteria(Criteria.where("descrizioneEn").regex(pattern, "i"));
			ret=db.find(query6, SportObj.class);
		}
		

		return ret;

	}

}